# Generated by Django 5.1.7 on 2025-03-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='page',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسم الصفحة'),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='اسم الدور'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Page Name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_add',
            field=models.BooleanField(default=False, verbose_name='Add Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Edit Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_view',
            field=models.BooleanField(default=False, verbose_name='View Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_add',
            field=models.BooleanField(default=False, verbose_name='Add Permission'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Permission'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Edit Permission'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view',
            field=models.BooleanField(default=False, verbose_name='View Permission'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
