"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
import dj_database_url




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file when present
# First pass does NOT override real environment variables
load_dotenv(BASE_DIR / ".env", override=False)

# Standardize environment selection: local | dev | production
ENVIRONMENT = os.getenv('ENVIRONMENT', 'local').lower()

# In local env, allow .env to override any pre-set shell/host vars to avoid
# accidentally using Railway's internal MYSQL_* values from the shell
if ENVIRONMENT == 'local':
    load_dotenv(BASE_DIR / ".env", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z06k@8=g!c)sw7dc)-#f21djg(@t13sodr_ka8=zxb@!6igjwu'

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.getenv('DEBUG')
if _debug_env is not None:
    DEBUG = _debug_env.lower() in ('1', 'true', 'yes', 'on')
else:
    DEBUG = ENVIRONMENT != 'production'

ALLOWED_HOSTS = [
    "dararabappbackendv01-production.up.railway.app",
    "dararabappbackendv01-dev.up.railway.app",
    "127.0.0.1",
    "localhost",
    ".railway.app",  # Allow all Railway subdomains
]
# Extend allowed hosts from env (comma separated)
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend([h.strip() for h in ALLOWED_HOSTS_ENV.split(',') if h.strip()])

# CSRF trusted origins - must include all origins that make POST requests
CSRF_TRUSTED_ORIGINS = [
    "https://dararabappbackendv01-production.up.railway.app",
    "https://dararabappbackendv01-dev.up.railway.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",  # Local Django dev server
    "http://127.0.0.1:8000",  # Local Django dev server
    "https://dararabappfrontendv01-production.up.railway.app",
    "https://dararabappfrontendv01-dev.up.railway.app",
]

# Add any additional origins from environment variable
CSRF_TRUSTED_ORIGINS_ENV = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(',') if origin.strip()])

# Additional CSRF settings for Railway/proxy environments
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF cookie SameSite attribute

# For Railway/proxy environments, trust proxy headers (keep enabled outside local)
USE_X_FORWARDED_HOST = ENVIRONMENT != 'local'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if ENVIRONMENT != 'local' else None

# In Django 5.x, CSRF checks are stricter - ensure we trust the proxy's origin detection
# This helps with Railway's proxy which may modify Origin/Referer headers
CSRF_TRUSTED_ORIGINS_DEBUG = DEBUG  # Store for potential conditional logic

# Ensure same-origin requests are trusted (for admin/forms on same domain)
# Django should handle this automatically, but be explicit in proxy environments
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'  # Default, but explicit



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'users',
    'inventory',
    'sales',
    'common',
    'django_filters',
    "rest_framework_simplejwt.token_blacklist",
    'whitenoise.runserver_nostatic',
    "csp",
]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Database configuration
# Prefer MYSQL_PUBLIC_URL for local; otherwise MYSQL_URL. In local, fallback to SQLite if none.
MYSQL_PUBLIC_URL = os.getenv('MYSQL_PUBLIC_URL')
MYSQL_URL = os.getenv('MYSQL_URL')

selected_db_url = None
if ENVIRONMENT == 'local':
    # Prefer public proxy URL in local environment
    selected_db_url = MYSQL_PUBLIC_URL or MYSQL_URL
else:
    selected_db_url = MYSQL_URL

if selected_db_url:
    DATABASES = {
        'default': dj_database_url.parse(selected_db_url, conn_max_age=600)
    }
    # Ensure MySQL options when using MySQL
    if DATABASES['default']['ENGINE'].endswith('mysql'):
        DATABASES['default'].setdefault('OPTIONS', {})
        DATABASES['default']['OPTIONS'].setdefault('init_command', "SET sql_mode='STRICT_TRANS_TABLES'")
        DATABASES['default']['OPTIONS'].setdefault('charset', 'utf8mb4')
    # Guard: in local env, don't allow internal host
    if ENVIRONMENT == 'local':
        host = DATABASES['default'].get('HOST')
        if host and host.endswith('.railway.internal'):
            raise Exception("❌ Detected internal Railway host in local env. Use MYSQL_PUBLIC_URL (gondola.proxy.rlwy.net:PORT).")
else:
    if ENVIRONMENT == 'local':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    else:
        raise Exception("❌ No database URL found. Set MYSQL_URL (and use MYSQL_PUBLIC_URL only for local).")

if DEBUG:
    print('--------------------------------')
    print(DATABASES)
    print('--------------------------------')
    if selected_db_url:
        src = 'MYSQL_PUBLIC_URL' if (ENVIRONMENT == 'local' and MYSQL_PUBLIC_URL) else 'MYSQL_URL'
        print(f"🔍 Database configured via {src}")
    else:
        print("🔍 Using local SQLite database")









# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create directories if they don't exist
STATIC_ROOT.mkdir(parents=True, exist_ok=True)
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# Simplified static file serving for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
   'DEFAULT_PAGINATION_CLASS': 'inventory.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    # DRF views are CSRF-exempt by default, but ensure it's explicit
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

CORS_ALLOW_ALL_ORIGINS = False  # ❌ Don't allow all, for security
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # ✅ Next.js Frontend
    "http://127.0.0.1:3000",  # ✅ Alternative Localhost
    "https://dararabappfrontendv01-production.up.railway.app",
    "https://dararabappfrontendv01-dev.up.railway.app",
]

# Allow extending CORS origins via env var (comma separated)
CORS_ALLOWED_ORIGINS_ENV = os.getenv('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS.extend([o.strip() for o in CORS_ALLOWED_ORIGINS_ENV.split(',') if o.strip()])



CORS_ALLOW_CREDENTIALS = True



AUTH_USER_MODEL = 'users.CustomUser'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # 🔹 Increase Access Token to 7 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # 🔹 Increase Refresh Token to 30 days
    'ROTATE_REFRESH_TOKENS': True,  # 🔹 Generate a new refresh token each time a refresh occurs
    'BLACKLIST_AFTER_ROTATION': True,  # 🔹 Blacklist old refresh tokens after they are rotated
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

SIMPLE_JWT["BLACKLIST_AFTER_ROTATION"] = True

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create directories if they don't exist
STATIC_ROOT.mkdir(parents=True, exist_ok=True)
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)


# Content Security Policy settings (django-csp 4.0+)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'connect-src': ("'self'",),
        'default-src': ("'self'",),
        'font-src': ("'self'", 'https://fonts.gstatic.com'),
        'frame-src': ("'none'",),
        'img-src': ("'self'", 'data:', 'https://dararab.co.uk', 'https://www.dararab.co.uk'),
        'media-src': ("'self'",),
        'object-src': ("'none'",),
        'script-src': ("'self'", "'unsafe-inline'", "'unsafe-eval'"),
        'style-src': ("'self'", "'unsafe-inline'", 'https://fonts.googleapis.com')
    }
}
