# Generated by Django 5.0.6 on 2025-03-26 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_list_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_list_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
