# Generated by Django 5.0.6 on 2025-03-24 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listtype',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.AddField(
            model_name='listtype',
            name='name_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
