# Generated by Django 5.0.6 on 2025-04-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_listitem_created_by_listitem_updated_by_and_more'),
        ('inventory', '0003_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='internal_layout',
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(default=1, max_length=255, verbose_name='Book Title (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Book Title (English)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_design',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='common.listitem'),
        ),
    ]
