# Generated by Django 5.2 on 2025-04-12 13:44

from django.db import migrations


def handle_duplicates(apps, schema_editor):
    Inventory = apps.get_model('inventory', 'Inventory')
    
    # Get all product-warehouse combinations
    from django.db.models import Count
    duplicates = Inventory.objects.values('product_id', 'warehouse_id').annotate(
        count=Count('id')).filter(count__gt=1)
    
    # For each duplicate combination
    for dup in duplicates:
        product_id = dup['product_id']
        warehouse_id = dup['warehouse_id']
        
        # Get all inventory records for this product-warehouse combination
        records = Inventory.objects.filter(
            product_id=product_id, 
            warehouse_id=warehouse_id
        ).order_by('id')
        
        # Keep the first record and merge quantities from others
        first_record = records.first()
        total_quantity = first_record.quantity
        
        # Add quantities from other records
        for record in records.exclude(id=first_record.id):
            total_quantity += record.quantity
            record.delete()
        
        # Update the first record with the total quantity
        first_record.quantity = total_quantity
        first_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RunPython(handle_duplicates, migrations.RunPython.noop),
    ]
