# Generated by Django 5.0.6 on 2025-04-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_price_remove_product_print_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Project',
            new_name='project',
        ),
    ]
