# Generated by Django 5.0.6 on 2025-04-18 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_project_product_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published_at',
        ),
        migrations.AddField(
            model_name='printrun',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
