# Generated by Django 5.0.6 on 2025-04-18 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_listitem_created_by_listitem_updated_by_and_more'),
        ('inventory', '0009_remove_product_published_at_printrun_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product'], name='inventory_i_product_f4f8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='printrun',
            index=models.Index(fields=['product', 'edition_number'], name='inventory_p_product_8eaac7_idx'),
        ),
    ]
