# Generated by Django 5.2 on 2025-12-20 15:10

import django.db.models.deletion
import inventory.models
from django.conf import settings
from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_listitem_created_by_listitem_updated_by_and_more'),
        ('inventory', '0010_inventory_inventory_i_product_f4f8f8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Note: royalties_type field may already exist in the database
        # Check if column exists before adding
        migrations.RunSQL(
            sql="""
                SET @dbname = DATABASE();
                SET @tablename = 'inventory_contract';
                SET @columnname = 'royalties_type_id';
                SET @preparedStatement = (SELECT IF(
                  (
                    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                    WHERE
                      (table_name = @tablename)
                      AND (table_schema = @dbname)
                      AND (column_name = @columnname)
                  ) > 0,
                  'SELECT 1;',
                  CONCAT('ALTER TABLE ', @tablename, ' ADD COLUMN ', @columnname, ' INT NULL, ADD CONSTRAINT inventory_contract_royalties_type_id_fk FOREIGN KEY (', @columnname, ') REFERENCES common_listitem(id) ON DELETE SET NULL;')
                ));
                PREPARE stmt FROM @preparedStatement;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE inventory_contract DROP FOREIGN KEY IF EXISTS inventory_contract_royalties_type_id_fk, DROP COLUMN IF EXISTS royalties_type_id;",
        ),
        # Note: language fields for Product and Project already exist in the database
        # Skipping their addition to avoid "Duplicate column name 'language_id'" error
        # If you need to add them, check the database first and use RunSQL with IF NOT EXISTS
        migrations.AlterField(
            model_name='product',
            name='cover_design',
            field=inventory.models.CoverDesignField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_type', to='common.listitem'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['approval_status'], name='project_approval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['progress_status'], name='project_progress_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['approval_status', 'progress_status'], name='project_approval_progress_idx'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='inventory_project',
        ),
    ]
