# Generated by Django 5.2 on 2026-01-05 14:50

import django.db.models.deletion
from django.db import migrations, models


def check_and_add_fields(apps, schema_editor):
    """Check if columns exist before adding them"""
    with schema_editor.connection.cursor() as cursor:
        # Check and add royalties_type_id if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
            WHERE table_schema = DATABASE()
            AND table_name = 'inventory_contract'
            AND column_name = 'royalties_type_id'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE inventory_contract 
                ADD COLUMN royalties_type_id INT NULL
            """)
            cursor.execute("""
                ALTER TABLE inventory_contract 
                ADD CONSTRAINT inventory_contract_royalties_type_id_fk 
                FOREIGN KEY (royalties_type_id) REFERENCES common_listitem(id) 
                ON DELETE SET NULL
            """)
        
        # Check and add language_id to product if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
            WHERE table_schema = DATABASE()
            AND table_name = 'inventory_product'
            AND column_name = 'language_id'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE inventory_product 
                ADD COLUMN language_id INT NULL
            """)
            cursor.execute("""
                ALTER TABLE inventory_product 
                ADD CONSTRAINT inventory_product_language_id_fk 
                FOREIGN KEY (language_id) REFERENCES common_listitem(id) 
                ON DELETE SET NULL
            """)
        
        # Check and add language_id to project if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
            WHERE table_schema = DATABASE()
            AND table_name = 'inventory_project'
            AND column_name = 'language_id'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE inventory_project 
                ADD COLUMN language_id INT NULL
            """)
            cursor.execute("""
                ALTER TABLE inventory_project 
                ADD CONSTRAINT inventory_project_language_id_fk 
                FOREIGN KEY (language_id) REFERENCES common_listitem(id) 
                ON DELETE SET NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_listitem_created_by_listitem_updated_by_and_more'),
        ('inventory', '0013_add_price_fields_to_product'),
    ]

    operations = [
        # First, check and add database columns if they don't exist
        migrations.RunPython(
            check_and_add_fields,
            migrations.RunPython.noop,  # No reverse needed - fields may already exist
        ),
        # Then update Django's state to know about these fields
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled above
            state_operations=[
                migrations.AddField(
                    model_name='contract',
                    name='royalties_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_royalties_type', to='common.listitem'),
                ),
                migrations.AddField(
                    model_name='product',
                    name='language',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_language', to='common.listitem'),
                ),
                migrations.AddField(
                    model_name='project',
                    name='language',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_language', to='common.listitem'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='printrun',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price ($)'),
        ),
        migrations.AlterField(
            model_name='printrun',
            name='price_omr',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)'),
        ),
    ]
