# Generated by Django 5.2 on 2026-07-28 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_contract_royalties_type_product_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('loss', 'Loss'), ('complimentary', 'Complimentary'), ('restock', 'Restock')], db_index=True, max_length=32)),
                ('quantity_delta', models.IntegerField(help_text='Signed change applied to inventory (+ in / − out)')),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference_code', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('invoice_item_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('transfer_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('return_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'occurred_at'], name='inventory_s_product_46406b_idx'), models.Index(fields=['product', 'occurred_at'], name='inventory_s_product_060ca2_idx'), models.Index(fields=['movement_type', 'occurred_at'], name='inventory_s_movemen_6e467f_idx')],
            },
        ),
    ]
