# Generated by Django 5.2 on 2026-07-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('loss', 'Loss'), ('reserved', 'Reserved'), ('complimentary', 'Complimentary'), ('restock', 'Restock')], db_index=True, max_length=32),
        ),
    ]
