# Generated by Django 5.2 on 2026-08-26 13:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_stockmovement_movement_type'),
        ('sales', '0004_productsalesstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField(help_text='Cycle start: project.created_at or previous settlement timestamp')),
                ('period_end', models.DateTimeField(blank=True, help_text='Last calculate time while open; set to settle time when settled', null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('eligible', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('calculation_details', models.JSONField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_settlements_calculated', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_settlements', to='inventory.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_settlements', to='inventory.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_settlements', to='inventory.project')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_settlements_settled', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Royalty Settlement',
                'verbose_name_plural': 'Royalty Settlements',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['contract', 'status'], name='sales_royal_contrac_e6b619_idx'), models.Index(fields=['project', 'status'], name='sales_royal_project_a75c75_idx'), models.Index(fields=['product', 'status'], name='sales_royal_product_b4d40a_idx'), models.Index(fields=['status', 'calculated_at'], name='sales_royal_status_83fa93_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('contract',), name='uniq_open_royalty_settlement_per_contract')],
            },
        ),
    ]
