# Generated by Django 5.2 on 2026-08-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_royaltysettlement'),
    ]

    operations = [
        # Conditional UniqueConstraint is not created on MySQL (W036), so only
        # remove it from Django state — do not DROP on the database.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='royaltysettlement',
                    name='uniq_open_royalty_settlement_per_contract',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='royaltysettlement',
            name='open_contract_id',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Set to contract_id while status=open; NULL when settled/cancelled',
                null=True,
                unique=True,
            ),
        ),
    ]
